# Generated by Django 5.2.17 on 2026-08-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('xp', models.FloatField(default=0)),
                ('atualizado_em', models.CharField(max_length=40)),
                ('identidade_json', models.TextField(default='{}')),
                ('tema_json', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilHabilidade',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('nivel', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilHistoricoHabilidade',
            fields=[
                ('em', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('itens_json', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilLogXp',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('em', models.CharField(max_length=40)),
                ('delta', models.FloatField()),
                ('origem', models.CharField(blank=True, default='', max_length=40)),
                ('rotulo', models.CharField(blank=True, default='', max_length=120)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', '-em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilRoadmapBonus',
            fields=[
                ('roadmap_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
