# Generated by Django 5.2.17 on 2026-08-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoFinal',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('roadmap_id', models.CharField(max_length=64, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('descricao', models.TextField(blank=True, default='')),
                ('stack_json', models.TextField(default='[]')),
                ('criterios_json', models.TextField(default='[]')),
                ('competencias_json', models.TextField(default='[]')),
                ('documentacao_json', models.TextField(default='{}')),
                ('topico_json', models.TextField(default='{}')),
                ('criado_em', models.CharField(max_length=40)),
                ('atualizado_em', models.CharField(max_length=40)),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoIntegrado',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('objetivo', models.TextField(blank=True, default='')),
                ('descricao', models.TextField(blank=True, default='')),
                ('stack_json', models.TextField(default='[]')),
                ('criterios_json', models.TextField(default='[]')),
                ('competencias_json', models.TextField(default='[]')),
                ('documentacao_json', models.TextField(default='{}')),
                ('topico_json', models.TextField(default='{}')),
                ('criado_em', models.CharField(max_length=40)),
                ('atualizado_em', models.CharField(max_length=40)),
                ('concluido', models.BooleanField(default=False)),
                ('concluido_em', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjetoEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64)),
                ('projeto_tipo', models.CharField(max_length=20)),
                ('projeto_id', models.CharField(max_length=64)),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('concluida', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['ordem'],
                'indexes': [models.Index(fields=['projeto_tipo', 'projeto_id'], name='projetos_pr_projeto_9e7b9f_idx')],
                'unique_together': {('projeto_tipo', 'projeto_id', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ProjetoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=64)),
                ('projeto_tipo', models.CharField(max_length=20)),
                ('projeto_id', models.CharField(max_length=64)),
                ('colecao', models.CharField(max_length=40)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('concluido', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('etapa_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['ordem'],
                'indexes': [models.Index(fields=['projeto_tipo', 'projeto_id'], name='projetos_pr_projeto_68d649_idx')],
                'unique_together': {('projeto_tipo', 'projeto_id', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ProjetoIntegradoRoadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadmap_id', models.CharField(max_length=64)),
                ('ordem', models.IntegerField(default=0)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps_rel', to='projetos.projetointegrado')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('projeto', 'roadmap_id')},
            },
        ),
    ]
