# Generated by Django 5.2.17 on 2026-08-17 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SidebarGrupo',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=120)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=500)),
                ('descricao', models.TextField(blank=True, default='')),
                ('prazo', models.CharField(blank=True, default='', max_length=40)),
                ('horas_estimadas', models.FloatField(default=0)),
                ('horas_reais', models.FloatField(default=0)),
                ('concluida', models.BooleanField(default=False)),
                ('concluida_em', models.CharField(blank=True, max_length=40, null=True)),
                ('tipo', models.CharField(default='pratica', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criterio_conclusao', models.TextField(blank=True, default='')),
                ('dificuldade', models.CharField(default='medio', max_length=20)),
                ('prioridade', models.CharField(default='media', max_length=20)),
                ('review_after_days', models.FloatField(default=0)),
                ('timer_ativo_desde', models.CharField(blank=True, max_length=40, null=True)),
                ('criada_em', models.CharField(max_length=40)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['ordem', 'criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Subtarefa',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=500)),
                ('concluida', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='roadmaps.tarefa')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(default='outro', max_length=20)),
                ('ordem', models.IntegerField(default=0)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='roadmaps.tarefa')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoTarefa',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('em', models.CharField(max_length=40)),
                ('tipo', models.CharField(default='editada', max_length=40)),
                ('detalhe', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='roadmaps.tarefa')),
            ],
            options={
                'ordering': ['ordem', 'em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=80)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attrs_rel', to='roadmaps.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia_id', models.CharField(max_length=64)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comps', to='roadmaps.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on_id', models.CharField(max_length=64)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deps', to='roadmaps.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_rel', to='roadmaps.tarefa')),
            ],
        ),
        migrations.CreateModel(
            name='SidebarAtribuicao',
            fields=[
                ('roadmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sidebar', serialize=False, to='roadmaps.roadmap')),
                ('ordem', models.IntegerField(default=0)),
                ('ordem_todos', models.IntegerField(default=0)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atribuicoes', to='roadmaps.sidebargrupo')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('ordem', models.IntegerField(default=0)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'indexes': [models.Index(fields=['roadmap'], name='roadmaps_co_roadmap_bdc96b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='tarefa',
            index=models.Index(fields=['roadmap'], name='roadmaps_ta_roadmap_4074d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tarefaatributo',
            unique_together={('tarefa', 'atributo')},
        ),
        migrations.AlterUniqueTogether(
            name='tarefacompetencia',
            unique_together={('tarefa', 'competencia_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tarefadep',
            unique_together={('tarefa', 'depends_on_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tarefatag',
            unique_together={('tarefa', 'tag')},
        ),
    ]
