export const IR_CONFIG = {
  maxQueries: 10,
  maxResultsPerProvider: 5,
  minScoreThreshold: 20,
  concurrency: 3,

  maxTopics: 3,
  minTopicScore: 5,
  topicKeywordMinLength: 5,
  maxImportantTerms: 12,
  importantTermMinLength: 4,

  providerQueryLimits: {
    default: 3,
    mock: 3,
    books: 2,
    brave: 3,
    github: 3,
    youtube: 3,
    stackoverflow: 3,
    reddit: 2,
  },

  providerConcurrency: {
    books: 1,
  },

  braveSearchLang: {
    pt: "pt-br",
    en: "en",
    es: "es",
  },
  languagePreferenceDefault: ["pt", "en"],

  deeplSourceLang: "PT",
  deeplTargetLang: "EN",

  scoring: {
    officialDoc: 50,
    githubRecent: 30,
    githubStarsHigh: 20,
    githubStarsMid: 10,
    githubStarsLow: 5,
    tutorialRecent: 20,
    videoRecent: 20,
    longVideo: 15,
    standardVideo: 8,
    shortVideo: -25,
    videoViewsHigh: 15,
    videoViewsMid: 8,
    article: 10,
    languagePrimary: 25,
    languageSecondary: 15,
    outdatedYear: -30,
    versionMismatch: -80,
    duplicate: -50,
    stackoverflowVotesHigh: 20,
    stackoverflowVotesMid: 10,
    stackoverflowAnswered: 15,
    bookSubstantial: 10,
    relevanceTech: 25,
    relevanceTopic: 20,
    relevanceKeyword: 8,
    relevanceKeywordMax: 24,
    importantTermHit: 8,
    importantTermRepeat: 5,
    importantTermRepeatMax: 25,
    missingImportantTerms: -30,
    missingTechnology: -25,
    wrongTechnology: -120,
    wrongGithubLanguage: -45,
    spamSnippet: -60,
    lowRelevance: -35,
  },

  githubStarsHigh: 1000,
  githubStarsMid: 100,
  githubStarsLow: 10,
  videoMinMinutes: 20,
  videoMaxShortMinutes: 2,
  videoViewsHigh: 100000,
  videoViewsMid: 10000,
  stackoverflowVotesHigh: 50,
  stackoverflowVotesMid: 10,
  bookMinPages: 200,

  recentGithubYears: 2,
  recentContentYears: 3,
  outdatedYearThreshold: 2017,
  titleSimilarityThreshold: 0.85,

  stopwords: new Set([
    // PT
    "a", "ao", "aos", "as", "até", "com", "como", "da", "das", "de", "del", "dela",
    "dele", "deles", "demais", "depois", "do", "dos", "e", "é", "ela", "ele", "eles",
    "em", "entre", "era", "eram", "essa", "esse", "esta", "este", "eu", "foi", "for",
    "foram", "há", "isso", "isto", "já", "la", "lá", "lhe", "lhes", "lo", "mais",
    "mas", "me", "mesmo", "meu", "minha", "muito", "na", "nas", "não", "nem", "no",
    "nos", "nós", "nossa", "nosso", "num", "numa", "o", "os", "ou", "para", "pela",
    "pelas", "pelo", "pelos", "por", "qual", "quando", "que", "quem", "se", "sem",
    "ser", "seu", "sua", "são", "também", "te", "tem", "tenho", "ter", "tu", "tua",
    "um", "uma", "uns", "umas", "vos", "vós", "sobre", "sob", "aprender", "aprenda",
    "entender", "usar", "criar", "fazer", "implementar", "estudar", "praticar", "funciona",
    // EN
    "the", "a", "an", "and", "or", "but", "in", "on", "at", "to", "for", "of", "with",
    "by", "from", "as", "is", "was", "are", "were", "be", "been", "being", "have",
    "has", "had", "do", "does", "did", "will", "would", "could", "should", "may",
    "might", "must", "shall", "can", "need", "it", "its", "this", "that", "these",
    "those", "i", "you", "he", "she", "we", "they", "what", "which", "who", "whom",
    "when", "where", "why", "how", "all", "each", "every", "both", "few", "more",
    "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same",
    "so", "than", "too", "very", "just", "about", "into", "through", "during",
    "before", "after", "above", "below", "between", "under", "again", "further",
    "then", "once", "here", "there", "any", "learn", "understand", "create", "make",
    "implement", "study", "practice", "using", "use", "work", "works", "working",
  ]),

  officialDocDomains: [
    "developer.mozilla.org",
    "laravel.com",
    "php.net",
    "web.dev",
    "docs.github.com",
    "nodejs.org",
    "python.org",
    "docker.com",
    "codeigniter.com",
    "typescriptlang.org",
    "dev.mysql.com",
    "git-scm.com",
    "react.dev",
    "vuejs.org",
    "kubernetes.io",
    "redis.io",
    "learn.microsoft.com",
    "dev.java",
    "oracle.com",
  ],

  queryTemplates: [
    "{tech} {topic}",
    "{tech} {topic} tutorial",
    "{tech} {topic} documentation",
    "{tech} {topic} example",
    "{tech} {topic} best practices",
    "{tech} {topic} guide",
    "{tech} {topic} github",
    "{tech} {topic} reddit",
    "{tech} {topic} youtube",
    "{tech} {topic} stackoverflow",
    "{tech} {topic} book",
    "{techTitle} {topicTitle}",
    "{techTitle} {topicTitle} Tutorial",
    "{techTitle} {topicTitle} Documentation",
    "{techTitle} {topicTitle} Example",
    "{techTitle} {topicTitle} Best Practices",
  ],

  githubUserAgent: "SistemaAprendizado-IR/1.0",
  redditUserAgent: "web:sistema-aprendizado-ir:v1.0 (learning roadmap tool)",
};
